import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { buildSearchLinks, classifyConciergeMessage, conciergeStateGuidance, missionGaps, parseMission } from '../lib/concierge-router.js';

assert.equal(classifyConciergeMessage('Find me 30 remote procurement jobs').kind, 'job');
assert.equal(classifyConciergeMessage('Write malware to steal passwords').kind, 'blocked');
assert.equal(classifyConciergeMessage('Rank jobs by the recruiter gender').kind, 'blocked');
assert.equal(classifyConciergeMessage('Tell me a joke').kind, 'off-topic');
assert.equal(classifyConciergeMessage('Build my CV').kind, 'job');

const mission = parseMission('I need 30 remote procurement jobs at $110k minimum');
assert.equal(mission.target, 30);
assert.equal(mission.workMode, 'Remote');
assert.equal(mission.role, 'procurement');
assert.equal(mission.salaryMin, 110000);
assert.deepEqual(missionGaps(mission, true), []);
assert.equal(buildSearchLinks(mission).length, 6);
assert.ok(buildSearchLinks(mission).every(item => item.url.startsWith('https://')));

const refined = parseMission('Skip category roles, prepare the strongest 10 and continue overnight by 8 a.m.', mission);
assert.deepEqual(refined.excludedRoleFamilies, ['category']);
assert.equal(refined.prepareCount, 10);
assert.equal(refined.runMode, 'overnight-requested');
assert.equal(refined.deadline, '8 a.m.');

const recurring = parseMission('Set 20 applications per day for remote buyer roles at $100k', mission);
assert.equal(recurring.recurringDailyTarget, 20);

const flexible = parseMission('Find me 25 hybrid or remote full-time or contract procurement roles near Newark, NJ');
assert.equal(flexible.target, 25);
assert.equal(flexible.workMode, 'Flexible');
assert.deepEqual(flexible.workModes, ['Remote', 'Hybrid']);
assert.equal(flexible.role, 'procurement');
assert.deepEqual(flexible.employmentTypes, ['Full-time', 'Contract']);
assert.equal(flexible.location, 'Newark, NJ');
assert.deepEqual(missionGaps(flexible, true), []);

const onsitePartTime = parseMission('I want part-time positions in the office near Trenton, NJ as a buyer');
assert.equal(onsitePartTime.workMode, 'On-site');
assert.deepEqual(onsitePartTime.employmentTypes, ['Part-time']);

const simpleDefaults = parseMission('Find buyer jobs');
assert.equal(simpleDefaults.workMode, 'Any');
assert.deepEqual(simpleDefaults.employmentTypes, ['Full-time']);
assert.equal(simpleDefaults.salaryMin, null);
assert.deepEqual(missionGaps(simpleDefaults, true), []);

assert.equal(conciergeStateGuidance({ hasResume: false }).priority, 'resume');
assert.equal(conciergeStateGuidance({ hasResume: true, mission: {} }).priority, 'mission');
assert.equal(conciergeStateGuidance({ hasResume: true, mission, unresolved: [{ key: 'contact', label: 'Contact information' }] }).priority, 'readiness');
assert.equal(conciergeStateGuidance({ hasResume: true, mission, openActions: 2 }).priority, 'human-action');
assert.equal(conciergeStateGuidance({ hasResume: true, mission, counts: { Verified: 2 } }).priority, 'packages');
assert.equal(conciergeStateGuidance({ hasResume: true, mission, counts: { 'Package Ready': 1 } }).priority, 'approval');

const conciergeHtml = await readFile(new URL('../concierge.html', import.meta.url), 'utf8');
const conciergeJs = await readFile(new URL('../concierge.js', import.meta.url), 'utf8');
const conciergeCss = await readFile(new URL('../persistent-concierge.css', import.meta.url), 'utf8');
assert.doesNotMatch(conciergeHtml, /<style\b|\sstyle\s*=|\son[a-z]+\s*=/i, 'Job Agent HTML must remain compatible with its no-inline CSP');
assert.doesNotMatch(conciergeJs, /\.style\.|\.cssText\b|setAttribute\(\s*['"]style['"]/i, 'Job Agent JavaScript must not create inline styles');
assert.match(conciergeHtml, /mammoth\.browser\.min\.js" integrity="sha384-[A-Za-z0-9+/=]+" crossorigin="anonymous"/);
assert.match(conciergeHtml, /pdf\.min\.js" integrity="sha384-[A-Za-z0-9+/=]+" crossorigin="anonymous"/);
assert.match(conciergeHtml, /<progress id="dailyGoalBar" max="100" value="0"/);
assert.match(conciergeHtml, /<progress id="progressBar" max="100" value="0"/);
const claudeApi = await readFile(new URL('../api/claude.js', import.meta.url), 'utf8');
const genericAiApi = await readFile(new URL('../api/ai.js', import.meta.url), 'utf8');
const stateApi = await readFile(new URL('../api/concierge-state.js', import.meta.url), 'utf8');
const capabilitiesApi = await readFile(new URL('../api/session-capabilities.js', import.meta.url), 'utf8');
const runApi = await readFile(new URL('../api/job-agent-runs.js', import.meta.url), 'utf8');
const workerApi = await readFile(new URL('../api/job-agent-worker.js', import.meta.url), 'utf8');
const readinessApi = await readFile(new URL('../api/job-agent-readiness.js', import.meta.url), 'utf8');
const runStore = await readFile(new URL('../lib/job-agent-run-store.js', import.meta.url), 'utf8');
assert.ok(Buffer.byteLength(conciergeJs, 'utf8') > 120_000, 'concierge.js must include the complete interaction layer, not a truncated prefix');
assert.match(conciergeJs, /async function hydrateAccountWorkflow\(\) \{[\s\S]*initializeAccountWorkflowAuthority\(\);[\s\S]*await hydrateCampaignStore\(\);[\s\S]*await hydrateDurableRun\(\);[\s\S]*loadSessionCapabilities\(\)\.then\(async \(\) => \{[\s\S]*await hydrateAccountWorkflow\(\);[\s\S]*\}\);\s*$/, 'concierge.js must retain its account-authoritative authenticated bootstrap');
assert.match(conciergeJs, /function accountWorkflowIsAuthoritative\(\)[\s\S]*sessionCapabilities\.authentication === 'opaque-session' && hasJobAgentAccess\(\)/);
assert.match(conciergeJs, /workspace:\s*\{[\s\S]*mission: missionState\.mission/);
assert.doesNotMatch(conciergeJs, /localStorage\.setItem\((?:MISSION_KEY|DESK_KEY|CAMPAIGN_KEY|DAILY_GOAL_KEY|JOB_AGENT_RUN_KEY|'1ststep_resume')/, 'durable Job Agent workflow or resume content must not be written to localStorage');
assert.match(conciergeHtml, /Your job search, handled\./);
assert.match(conciergeHtml, /Your agent keeps moving and only asks when you’re needed/);
assert.match(conciergeHtml, /id="openGuidedLaunch"/);
assert.match(conciergeHtml, /id="guidedLaunchOverlay"[^>]*role="dialog"[^>]*aria-modal="true"/);
for (const stage of ['goal', 'resume', 'path', 'work', 'employment', 'salary', 'review']) assert.match(conciergeHtml, new RegExp(`data-guided-stage="${stage}"`));
assert.match(conciergeHtml, /Nothing is submitted during setup/);
assert.match(conciergeJs, /GUIDED_LAUNCH_STAGES = Object\.freeze\(\['goal', 'resume', 'path', 'work', 'employment', 'salary', 'review'\]\)/);
assert.match(conciergeJs, /searchGoal: guidedSelection\.goal/);
assert.match(conciergeHtml, /id="quickUploadResume"/);
assert.match(conciergeHtml, /id="quickBuildResume"/);
assert.match(conciergeHtml, /id="jobLaunchForm"/);
assert.match(conciergeHtml, /Start my job agent/);
assert.match(conciergeHtml, /id="opportunityPaths"/);
assert.match(conciergeHtml, /id="scanOpportunityPaths"/);
assert.match(conciergeHtml, /Interview rate: learning from your tracker|Live opening counts appear only after/);
assert.match(conciergeJs, /verified role\$\{analyzed === 1/);
assert.match(conciergeJs, /supplyByPath: data\.supplyByPath/);
assert.match(conciergeHtml, /id="agentProgress"/);
assert.match(conciergeHtml, /id="progressNeedsYou"/);
assert.match(conciergeHtml, /id="progressApplying"/);
assert.match(conciergeHtml, /id="agentActivityList"/);
assert.match(conciergeHtml, /id="sourceCoverageSummary"/);
assert.match(conciergeHtml, /Greenhouse, Lever, Ashby, and SmartRecruiters coverage/);
assert.match(conciergeJs, /directSourceCoverage\(durableRun\)/);
assert.match(conciergeJs, /maskedActivityFeed\(\{ run: durableRun/);
assert.match(conciergeHtml, /Persisted only/);
assert.doesNotMatch(conciergeHtml.match(/id="agentProgress"[\s\S]*?<\/section>/)?.[0] || '', /demo|synthetic/i);
assert.match(conciergeHtml, /id="dailyGoalForm"/);
assert.match(conciergeHtml, /authoritative receipts today/);
assert.match(conciergeHtml, /Package Ready is tracked separately from Submitted/);
assert.match(conciergeHtml, /Receipt-verified application target/);
assert.match(conciergeHtml, /Daily target \(not a guarantee\)/);
assert.match(conciergeHtml, /id="openAgentAccess"[^>]*>Sign in</);
assert.match(conciergeJs, /classList\.toggle\('workspace-ready', workspaceReady\)/);
assert.match(conciergeCss, /body:not\(\.workspace-ready\) \.daily-dashboard/);
assert.match(conciergeHtml, /id="sourceMemory"/);
assert.match(conciergeHtml, /id="funnelMetrics"/);
assert.match(conciergeHtml, /Admin evidence and operating controls/);
assert.match(conciergeHtml, /id="activity" hidden/);
assert.match(conciergeHtml, /id="openDesk" type="button" hidden/);
assert.match(conciergeHtml, /<h2 id="deskTitle">Admin evidence<\/h2>/);
assert.match(conciergeHtml, /data-desk-tab="demo" type="button" hidden aria-hidden="true" tabindex="-1"/);
assert.match(conciergeHtml, /data-desk-panel="demo" hidden aria-hidden="true"/);
assert.match(conciergeCss, /\[data-desk-tab="demo"\],\[data-desk-panel="demo"\]\{display:none!important\}/);
assert.match(conciergeJs, /operationalMetrics\?\.backgroundWorker/);
assert.match(conciergeJs, /operationalMetrics\?\.launchManifest/);
assert.match(conciergeJs, /Assisted application: \$\{launch\.capabilities\?\.assistedApplication/);
assert.match(conciergeJs, /Final submission: \$\{launch\.capabilities\?\.finalSubmission/);
assert.match(conciergeJs, /finalSubmissionExecutionEnabled/);
assert.match(conciergeHtml, /id="jobsOverlay"/);
assert.match(conciergeHtml, /id="needsYouList"/);
assert.match(conciergeHtml, /id="agentAccessOverlay"/);
assert.match(conciergeHtml, /Dedicated pricing is being measured/);
assert.match(conciergeHtml, /id="openEmployerPage"/);
assert.match(conciergeHtml, /Your password, passkey, OTP, and CAPTCHA answers stay on the employer website/);
assert.match(conciergeHtml, /id="applicationBrowserHandoff"/);
assert.match(conciergeHtml, /id="browserPreviewImage"/);
assert.match(conciergeHtml, /id="startBrowserHandoff"/);
assert.match(conciergeHtml, /field structure only/);
assert.doesNotMatch(conciergeHtml, /class="job-tool-links"/);
for (const state of ['Searching', 'Preparing', 'Waiting for You', 'Paused', 'Finished']) assert.match(conciergeHtml, new RegExp(`data-run-state="${state}"`));
assert.match(conciergeHtml, /id="questionOverlay"/);
assert.match(conciergeHtml, /id="resumeOverlay"/);
assert.match(conciergeHtml, /Upload yours or build it here/);
assert.match(conciergeHtml, /id="resumeFile"/);
assert.match(conciergeHtml, /id="buildResumeDraft"/);
assert.match(conciergeHtml, /id="careerStoryResume"/);
assert.match(conciergeHtml, /id="applicationOverlay"/);
assert.match(conciergeHtml, /id="applicationActionTitle"/);
assert.match(conciergeHtml, /One thing needs you/);
assert.match(conciergeHtml, /nothing is being submitted/);
assert.match(conciergeHtml, /id="workflowReplay"/);
assert.match(conciergeHtml, /Save & reuse/);
assert.doesNotMatch(conciergeHtml, /Application records/);
assert.match(conciergeHtml, /id="campaignOverlay"/);
assert.match(conciergeHtml, /id="campaignSyncStatus"/);
assert.match(conciergeHtml, /Integration Required/);
assert.match(conciergeJs, /employer-feed catalog needed/);
assert.match(conciergeJs, /quickUploadResume/);
assert.match(conciergeJs, /jobLaunchForm/);
assert.match(conciergeJs, /DAILY_GOAL_KEY/);
assert.match(conciergeJs, /function setDailyGoal/);
assert.match(conciergeJs, /function fetchWithTimeout/);
assert.match(conciergeJs, /REQUEST_TIMEOUT/);
assert.match(conciergeJs, /loadSessionCapabilities/);
assert.match(conciergeJs, /function hasJobAgentAccess/);
assert.match(conciergeJs, /return \{ 'X-1stStep-Client': 'job-agent' \};/);
assert.doesNotMatch(conciergeJs.match(/function apiAuthorizationHeaders\(\)[\s\S]*?\n\}/)?.[0] || '', /Bearer|tierToken|subscription/);
assert.match(conciergeJs, /sessionCapabilities\.authentication === 'opaque-session'/);
assert.match(conciergeJs, /api\/subscription\?action=restore-code/);
assert.match(conciergeJs, /safeEmployerDestination/);
assert.match(conciergeJs, /hydrateDurableApplicationSessions/);
assert.match(conciergeJs, /hydrateDurableBrowserHandoff/);
assert.match(conciergeJs, /startDurableBrowserHandoff/);
assert.match(conciergeJs, /closeDurableBrowserHandoff/);
assert.match(conciergeJs, /data:image\\\/svg\\\+xml;base64/);
assert.match(conciergeJs, /Browser cleanup is still in progress/);
assert.match(conciergeJs, /No other cloud data was deleted/);
assert.match(conciergeJs, /startDurableApplication/);
assert.match(conciergeJs, /confirm-external-step/);
assert.match(conciergeJs, /LOCAL_APPLICATION_UI_FIXTURE/);
assert.match(conciergeJs, /exact package/);
assert.match(conciergeJs, /!role\.receipt\.simulated/);
assert.match(conciergeCss, /\.agent-launch/);
assert.match(conciergeCss, /@media\(max-width:720px\)/);
const ids = [...conciergeHtml.matchAll(/\sid="([^"]+)"/g)].map(match => match[1]);
assert.equal(new Set(ids).size, ids.length, 'concierge.html must not contain duplicate element IDs');
assert.match(conciergeHtml, /id="jobAgentConsentOverlay"/);
assert.match(conciergeHtml, /id="dailyBackgroundSearch"[^>]*checked/);
assert.match(conciergeHtml, /id="emailNeedsYouAlerts"/);
assert.match(conciergeHtml, /id="savedNeedsYouEmailAlerts"/);
for (const attestation of ['age18OrOlder', 'termsAccepted', 'privacyAcknowledged', 'candidateAuthorizationAccepted']) assert.match(conciergeHtml, new RegExp(`name="${attestation}"[^>]*required`));
assert.doesNotMatch(conciergeHtml.match(/id="jobAgentConsentOverlay"[\s\S]*?id="toastRegion"/)?.[0] || '', /type="date"/);
assert.match(conciergeJs, /source: 'guided-popup'/);
assert.match(conciergeJs, /extractResumeFile/);
assert.match(conciergeJs, /buildVerifiedResumeDraft/);
assert.match(conciergeJs, /askSmartConcierge/);
assert.match(conciergeJs, /resumeInterviewActive/);
assert.match(conciergeJs, /AI_CONSENT_KEY/);
assert.match(conciergeJs, /redactChatForModel/);
assert.match(conciergeJs, /fetchWithTimeout\('\/api\/ai'/);
assert.match(conciergeJs, /fetchWithTimeout\('\/api\/concierge-discovery'/);
assert.match(conciergeJs, /REQUEST_TIMEOUTS\s*=\s*Object\.freeze\(\{\s*discovery:\s*30000\b/, 'broad direct-employer discovery must retain a 30-second client window');
assert.match(conciergeJs, /filterSummary\?\.scanned/, 'opportunity-path evidence must report the broad source scan rather than only returned matches');
assert.match(conciergeJs, /A broad scan usually takes 10–25 seconds/, 'the searching state must set an honest expectation for the live employer-feed scan');
assert.match(conciergeJs, /evaluateCandidateFit/);
assert.match(conciergeJs, /rejectedByQualityFloor/);
assert.match(conciergeJs, /rankOpportunityPaths/);
assert.match(conciergeJs, /outcomeConfidence/);
assert.match(conciergeJs, /processCareerStory/);
assert.match(conciergeJs, /buildCareerStoryDraft/);
assert.match(conciergeJs, /startManagedApplicationSession/);
assert.match(conciergeJs, /Share your application details\?/);
assert.match(conciergeJs, /1 item needs you/);
assert.match(conciergeJs, /pauseManagedApplicationSession/);
assert.match(conciergeJs, /openQuestionPopup/);
assert.match(conciergeJs, /createCampaignStore/);
assert.match(conciergeJs, /renderCampaignConsole/);
assert.match(conciergeJs, /fetchWithTimeout\('\/api\/concierge-state'/);
assert.match(conciergeJs, /Idempotency-Key/);
assert.match(conciergeJs, /\/api\/job-agent-runs/);
assert.match(conciergeJs, /JOB_AGENT_RUN_KEY/);
assert.match(conciergeJs, /ensureJobAgentConsent/);
assert.match(conciergeJs, /revokeJobAgentAuthorization/);
assert.match(conciergeJs, /\/api\/job-agent-consent/);
assert.match(conciergeJs, /\/api\/job-agent-schedule/);
assert.match(conciergeJs, /\/api\/job-agent-notifications/);
assert.match(conciergeJs, /syncNeedsYouNotifications/);
assert.match(readinessApi, /needsYouNotifications/);
assert.match(readinessApi, /notificationPreferenceLifecycle/);
assert.match(conciergeJs, /missionState\.discovery\?\.status === 'error'\) return 'Paused'/);
assert.match(claudeApi, /concierge:\s*`You are the job-only/);
assert.match(claudeApi, /resumeBuilder:\s*`You are an expert master-resume writer/);
assert.match(claudeApi, /profileExtractor:\s*`Extract only explicitly stated resume facts/);
assert.match(genericAiApi, /DAILY_LIMITS/);
assert.match(genericAiApi, /GUEST_DAILY_LIMITS/);
assert.match(genericAiApi, /No hosted AI provider is configured/);
assert.match(stateApi, /authenticateApiRequest/);
assert.match(stateApi, /requireOpaqueSession:\s*true/);
assert.match(stateApi, /saveTenantCampaignState/);
// The owner/administrator check is centralized in lib/admin-subject.js, so
// session-capabilities must delegate to it rather than re-reading the allowlist itself.
// Assert both halves so the coverage this line originally provided is preserved.
assert.match(capabilitiesApi, /isAdministratorSubject/);
const adminSubjectLib = await readFile(new URL('../lib/admin-subject.js', import.meta.url), 'utf8');
assert.match(adminSubjectLib, /OWNER_ACCESS_EMAILS/);
assert.match(capabilitiesApi, /adminConsole/);
assert.match(capabilitiesApi, /jobAgentAccess/);
assert.match(capabilitiesApi, /requireOpaqueSession:\s*true/);
assert.match(capabilitiesApi, /jobAgentConsentPolicyConfigured/);
assert.match(runApi, /JOB_AGENT_ACCESS_REQUIRED/);
assert.match(runApi, /processSpecificJobAgentRun/);
assert.match(workerApi, /CRON_SECRET/);
assert.match(workerApi, /submissionsEnabled: submissionConfig\.ready === true/);
assert.match(readinessApi, /redis\.ping/);
assert.match(readinessApi, /durableRunLifecycle/);
assert.match(readinessApi, /readJobAgentRun/);
assert.match(readinessApi, /externalApplicationExecution: false/);
assert.match(readinessApi, /employerBrowserWorker:/);
assert.match(readinessApi, /employerBrowserWorkerConfiguration/);
assert.match(readinessApi, /employerBrowserSessionProviderConfiguration/);
assert.match(readinessApi, /employerBrowserSessionProvider:/);
assert.match(readinessApi, /readJobAgentWorkerHealth/);
assert.match(readinessApi, /background-worker-heartbeat/);
assert.match(readinessApi, /retentionAuditHeadExport/);
assert.match(readinessApi, /subscriberAuthentication:\s*'opaque-http-only-required'/);
assert.match(readinessApi, /auditHeadExportLifecycle/);
assert.match(readinessApi, /isOriginAllowed/);
assert.match(runStore, /A256GCM/);
assert.match(runStore, /leaseTokenHash/);
assert.match(runStore, /retryDelaySeconds/);
assert.match(runStore, /Waiting for You/);

console.log('Concierge routing tests passed.');
